# Grupo 3
Uso de f-string, diccionarios y listas, matrices, operaciones con matrices.


1- Use f-string para concaternar textos o valores numéricos. De 2 ejemplos.


In [1]:
#ejemplo 1
a <- "cobre"
print( a )

[1] "cobre"


In [2]:
b <- "café"
print( b )

[1] "café"


In [3]:
c <- "gas natural"
print( c )

[1] "gas natural"


In [4]:
x1 <- "Los productos tradicionales que más se exportaron en el mes de enero son"
print( x1 )

[1] "Los productos tradicionales que más se exportaron en el mes de enero son"


In [5]:
#install.packages("devtools")
library(glue)

In [6]:
y1 <- glue('{x1} el {a}, {b} y {c}')
y1

Los productos tradicionales que más se exportaron en el mes de enero son el cobre, café y gas natural

In [7]:
#ejemplo 2
d <- "Huancayo"
print( d )

[1] "Huancayo"


In [8]:
e <- "Lima"
print( e )

[1] "Lima"


In [9]:
f <- "Tacna"
print( f )

[1] "Tacna"


In [10]:
x2 <- "El paro de transportistas ha generado revueltas en"
print( x2 )

[1] "El paro de transportistas ha generado revueltas en"


In [11]:
y2 <- glue('{x2} {d}, {e} y {f} ')
y2

El paro de transportistas ha generado revueltas en Huancayo, Lima y Tacna

## Diccionarios y listas


2- Crear una Lista de 3 distritos de Lima, añadir 2 distritos del Callao. Extraer el primer y último elemento usando el Indexing

In [12]:
remove(list=ls())
mylist <- list()

In [13]:
distLima <- list('SAN MIGUEL', 'JESUS MARÍA','LINCE')
distLima

[[1]]
[1] "SAN MIGUEL"

[[2]]
[1] "JESUS MARÍA"

[[3]]
[1] "LINCE"

In [14]:
distCallao <- list("LA PERLA", "BELAVISTA")
distCallao

[[1]]
[1] "LA PERLA"

[[2]]
[1] "BELAVISTA"

In [15]:
# list(distLima, distCallao)
append(distLima, distCallao)

[[1]]
[1] "SAN MIGUEL"

[[2]]
[1] "JESUS MARÍA"

[[3]]
[1] "LINCE"

[[4]]
[1] "LA PERLA"

[[5]]
[1] "BELAVISTA"

In [16]:
#distLima <- list('SAN MIGUEL', 'JESUS MARÍA','LINCE')
distLima[2:3]
distLima[-1]

[[1]]
[1] "JESUS MARÍA"

[[2]]
[1] "LINCE"

[[1]]
[1] "JESUS MARÍA"

[[2]]
[1] "LINCE"

In [17]:
#distCallao <- list("LA PERLA", "BELAVISTA")
distCallao[0:1]

[[1]]
[1] "LA PERLA"

3- Crear un diccionario con los 5 distritos del ejercicio a. Incluir información de población proyectada e incidencia de pobreza (limite superior).Use la información del Mapa de Pobreza 2018

In [18]:
poblacion <- list("San Miguel" = 173309,
                  "Jesus Maria" = 81743,
                  "Lince" = 59578,
                  "La Perla" = 64454,
                  "Bellavista" = 80704)
poblacion

$`San Miguel`
[1] 173309

$`Jesus Maria`
[1] 81743

$Lince
[1] 59578

$`La Perla`
[1] 64454

$Bellavista
[1] 80704

In [19]:
poblacion$"Jesus Maria"

[1] 81743

In [20]:
pobreza <- list("San Miguel" = 2.2,
                "Jesus Maria" = 0.8,
                "Lince" = 2.2,
                "La Perla" = 4.1,
                "Bellavista" = 6.2 )
pobreza


$`San Miguel`
[1] 2.2

$`Jesus Maria`
[1] 0.8

$Lince
[1] 2.2

$`La Perla`
[1] 4.1

$Bellavista
[1] 6.2

In [21]:
pobreza$"Bellavista"

[1] 6.2

4-Muestre la información de pobreza y de población de 3 distritos



In [22]:
#informacion de la incidencia de pobreza de tres distritos

pobreza[(2:4)]

$`Jesus Maria`
[1] 0.8

$Lince
[1] 2.2

$`La Perla`
[1] 4.1

In [23]:
#informacion de poblacion proyectada de tres distritos
poblacion[(2:4)]

$`Jesus Maria`
[1] 81743

$Lince
[1] 59578

$`La Perla`
[1] 64454

## Matrices


5- Crear matrices y dar dos ejemplos de concatenación. Unión vertical y horizontal.

In [24]:
m <- c(1:8)

In [25]:
#union horizontal
matrix1 <- matrix(m, nrow = 2, byrow = TRUE)
print(matrix1)

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8


In [26]:
n <- c(1:8)

In [27]:
#union vertical
matrix2 <- matrix(n, nrow = 2, byrow = FALSE)
print(matrix2)

     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8


6- Crear una matriz de dimensión 4x8, seleccionar las ultimas dos columnas y primeras 3 filas.


In [28]:
y <- matrix(1:32, 4, 8)
y

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 1    5     9   13   17   21   25   29  
[2,] 2    6    10   14   18   22   26   30  
[3,] 3    7    11   15   19   23   27   31  
[4,] 4    8    12   16   20   24   28   32

In [29]:
#ultimas dos columnas de la matriz
y[,c(7:8)]

[,1] [,2]
[1,] 25   29  
[2,] 26   30  
[3,] 27   31  
[4,] 28   32

In [30]:
#primeras tres filas de la matriz
y[c(1:3), ]

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 1    5     9   13   17   21   25   29  
[2,] 2    6    10   14   18   22   26   30  
[3,] 3    7    11   15   19   23   27   31

## Operaciones con matrices


7- Obtener el estimador de la varianza del término de perturbación



In [31]:
#install.packages("RcppEigen")
#library("RcppEigen")

In [32]:
#install.packages("bootstrap")
#library(bootstrap)

In [33]:
#solución al modelo multivariado
set.seed(123)

x1 <- runif(15)
x2 <- runif(15)
x3 <- runif(15)
#random.seed(123)
e <- rnorm(15)
 
# Poblacional regression (Data Generating Process GDP)
 
Y <- 12 + 3*x1 + 5*x2 + 1*x3 + e


In [34]:
#matriz X
X <- cbind(matrix(1,15), x1,x2,x3)
print(X)


               x1         x2         x3
 [1,] 1 0.2875775 0.89982497 0.96302423
 [2,] 1 0.7883051 0.24608773 0.90229905
 [3,] 1 0.4089769 0.04205953 0.69070528
 [4,] 1 0.8830174 0.32792072 0.79546742
 [5,] 1 0.9404673 0.95450365 0.02461368
 [6,] 1 0.0455565 0.88953932 0.47779597
 [7,] 1 0.5281055 0.69280341 0.75845954
 [8,] 1 0.8924190 0.64050681 0.21640794
 [9,] 1 0.5514350 0.99426978 0.31818101
[10,] 1 0.4566147 0.65570580 0.23162579
[11,] 1 0.9568333 0.70853047 0.14280002
[12,] 1 0.4533342 0.54406602 0.41454634
[13,] 1 0.6775706 0.59414202 0.41372433
[14,] 1 0.5726334 0.28915974 0.36884545
[15,] 1 0.1029247 0.14711365 0.15244475


In [35]:
#matriz de coeficientes
beta <- solve(t(X) %*% X) %*% (t(X) %*% Y)
beta



[,1]     
   10.346849
x1  4.426510
x2  4.581780
x3  2.476723

In [36]:
#modelo y estimado
yhat <- X %*% beta
print(yhat)


          [,1]
 [1,] 18.12776
 [2,] 17.19855
 [3,] 14.06058
 [4,] 17.72815
 [5,] 18.94412
 [6,] 15.80755
 [7,] 17.73728
 [8,] 17.76779
 [9,] 18.13135
[10,] 15.94603
[11,] 18.18229
[12,] 15.87304
[13,] 17.09303
[14,] 15.12001
[15,] 11.85405


In [37]:
#matriz de los errores estimados
e_hat <- Y - yhat
print(e_hat)

              [,1]
 [1,] -0.888576175
 [2,] -0.786324755
 [3,]  1.137961286
 [4,] -0.789418085
 [5,] -0.491135066
 [6,]  0.436098846
 [7,]  0.754448464
 [8,]  0.008347888
 [9,] -0.499041013
[10,]  0.334359072
[11,]  0.244253353
[12,]  1.508570306
[13,]  0.172719311
[14,]  0.742324508
[15,] -1.884587940


In [38]:
#matriz transpuesta de los errores estimados
e_hat_t <- t(e_hat)
print(e_hat_t)

           [,1]       [,2]     [,3]       [,4]       [,5]      [,6]      [,7]
[1,] -0.8885762 -0.7863248 1.137961 -0.7894181 -0.4911351 0.4360988 0.7544485
            [,8]      [,9]     [,10]     [,11]   [,12]     [,13]     [,14]
[1,] 0.008347888 -0.499041 0.3343591 0.2442534 1.50857 0.1727193 0.7423245
         [,15]
[1,] -1.884588


In [39]:
#suma de los cuadrados de los residuos: SCR
SCR <- e_hat_t  %*%  e_hat
print(SCR)

        [,1]
[1,] 11.1555


In [40]:
obs <- 15
k <- 5

In [41]:
#estimador de la varianza del termino de perturbación
sigma_estimate <- SCR / (15 - 5)
print(sigma_estimate)

        [,1]
[1,] 1.11555


8- matriz de varianza y covarianza de los coeficientes



In [42]:
# matriz X transpuesta
X_t <- t(X)
print(X_t)

        [,1]      [,2]       [,3]      [,4]       [,5]      [,6]      [,7]
   1.0000000 1.0000000 1.00000000 1.0000000 1.00000000 1.0000000 1.0000000
x1 0.2875775 0.7883051 0.40897692 0.8830174 0.94046728 0.0455565 0.5281055
x2 0.8998250 0.2460877 0.04205953 0.3279207 0.95450365 0.8895393 0.6928034
x3 0.9630242 0.9022990 0.69070528 0.7954674 0.02461368 0.4777960 0.7584595
        [,8]      [,9]     [,10]     [,11]     [,12]     [,13]     [,14]
   1.0000000 1.0000000 1.0000000 1.0000000 1.0000000 1.0000000 1.0000000
x1 0.8924190 0.5514350 0.4566147 0.9568333 0.4533342 0.6775706 0.5726334
x2 0.6405068 0.9942698 0.6557058 0.7085305 0.5440660 0.5941420 0.2891597
x3 0.2164079 0.3181810 0.2316258 0.1428000 0.4145463 0.4137243 0.3688455
       [,15]
   1.0000000
x1 0.1029247
x2 0.1471136
x3 0.1524447


In [43]:
#multiplicar transpuesta por X
Xt_X <- X_t %*% X
Xt_X

x1       x2       x3      
   15.000000 8.545771 8.626234 6.870941
x1  8.545771 6.044193 4.990767 3.724728
x2  8.626234 4.990767 6.246934 3.660933
x3  6.870941 3.724728 3.660933 4.379974

In [44]:
#inversa de la matrix X transpuesta por la matriz X
invXt_X <- solve(Xt_X)
print(invXt_X)

                       x1          x2         x3
    0.9583254 -0.54348504 -0.54681721 -0.5841135
x1 -0.5434850  0.87299650 -0.02260722  0.1290744
x2 -0.5468172 -0.02260722  0.82179594  0.1901414
x3 -0.5841135  0.12907436  0.19014142  0.8759293


In [45]:
#matriz de var-cov
var_cov <- 1.11555 * invXt_X
var_cov

x1          x2          x3        
    1.0690599 -0.60628474 -0.61000194 -0.6516078
x1 -0.6062847  0.97387125 -0.02521948  0.1439889
x2 -0.6100019 -0.02521948  0.91675446  0.2121123
x3 -0.6516078  0.14398890  0.21211226  0.9771429

9 - Matriz generadora de residuos


### Matriz generadora de residuos


 𝑀=𝐼−𝑋(𝑋′𝑋)^−1𝑋'

In [46]:
#creación de la matriz identidad
I <- diag(15)


In [47]:
# multiplicacion de la matriz: parte 1
matrizX <- X %*% invXt_X


In [48]:
#multiplicación de la matriz: parte 2
matrizX1 <- matrizX %*% X_t

In [49]:
M <- I - matrizX1
print(M)

              [,1]        [,2]         [,3]        [,4]         [,5]
 [1,]  0.524101330 -0.11172601 -0.008928397 -0.07413468  0.065800416
 [2,] -0.111726014  0.65707113 -0.209839442 -0.31361905  0.064755870
 [3,] -0.008928397 -0.20983944  0.690570427 -0.15987948  0.153201084
 [4,] -0.074134678 -0.31361905 -0.159879476  0.69864641 -0.005614740
 [5,]  0.065800416  0.06475587  0.153201084 -0.00561474  0.640847796
 [6,] -0.290802263  0.12032070  0.002914380  0.14267468  0.004789907
 [7,] -0.258457457 -0.14013864 -0.049360875 -0.12285840 -0.003895804
 [8,]  0.083001894 -0.05093050  0.010303252 -0.09139548 -0.227501293
 [9,] -0.159489343  0.06763137  0.106515902  0.04087621 -0.190896413
[10,] -0.011863804  0.05796396 -0.027826573  0.04703752 -0.113975311
[11,]  0.104445467 -0.02829885  0.049184802 -0.08097243 -0.278341274
[12,] -0.056798521 -0.02739908 -0.086648205 -0.02106985 -0.040952339
[13,] -0.032643194 -0.07486643 -0.045012247 -0.08586824 -0.110341204
[14,]  0.081185502 -0.09032503 -0.